name: firedanger_dev
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - cartopy=0.19.0
  - xarray=0.16.1
  - dask=2021.6.0
  - numba=0.53.1
  - numpy=1.20.2
  - scipy=1.6.3
  - pandas=1.2.4
  - matplotlib=3.4.1
  - pip=21.1.1
  - netcdf4=1.5.6
  - cftime=1.5.0
